[workspace]
members = ["libs/s-program-sdk", "program-simulator", "test-utils"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]

anyhow = "^1"
assert_cmd = "^2"
async-trait = ">=0.1"
bincode = "^1"
borsh = ">=0.9"
bs58 = "^0.4"
bytemuck = "^1"
clap = { version = "^4", features = ["derive"] }
data-encoding = "^2"
inquire = { version = "^0.7", default-features = false, features = [
    "crossterm",
] }
jupiter-amm-interface = "~0.4"
lazy_static = "^1"
num-derive = ">=0.3"
num-traits = ">=0.2"
proptest = "^1"
rust_decimal = ">=1.0" # anything >1.32 uses borsh ^1
sanctum-macros = "^1.2"
serde = "^1.0.197"
serde_json = "^1"
spl-pod = ">=0.1.0"
spl-token = ">=0.1.0"
spl-token-2022 = ">=0.1.0"
spl-token-metadata-interface = ">=0.1.0"
spl-associated-token-account = ">=0.1.0"
static_assertions = "^1"
thiserror = "^1"
tokio = "^1"

# solana libraries (not pure rust)
# Use >=1 for flexibility for library users, but lock to 1.17.6 for deploy.
solana-account-decoder = ">=1, <2"
solana-client = ">=1, <2"
solana-program = ">=1, <2"
solana-program-test = ">=1, <2"
solana-remote-wallet = ">=1, <2"
solana-rpc-client-api = ">=1, <2"
solana-sdk = ">=1, <2"
solana-transaction-status = ">=1, <2"
solana-banks-interface = ">=1, <2"

program-simulator = { path = "./program-simulator" }
s-program-sdk = { path = "./libs/s-program-sdk" }
s-controller = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
s-controller-lib = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
s_controller_interface = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
flat-fee = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
flat-fee-lib = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
spl-calculator = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
spl-calculator-lib = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
marinade-calculator = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
marinade-calculator-lib = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
lido-calculator = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
lido-calculator-lib = { git = "https://github.com/moose-labs/S", branch = "custom_address" }
