[package]
name = "s-program-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "s_program_sdk"

[dependencies]
solana-program = { workspace = true }

[dev-dependencies]
spl-token = { workspace = true }

tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
test-utils = { workspace = true }
solana-sdk = { workspace = true }
flat-fee-lib = { workspace = true, features = ["testing"] }
no-fee-pricing-program = { workspace = true, features = ["testing"] }

s-controller-lib = { workspace = true, features = ["testing"] }
spl-calculator-lib = { workspace = true }
