[package]
name = "program-simulator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "program_simulator"

[dependencies]
solana-program = { workspace = true }
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
solana-banks-interface = { workspace = true }
borsh = "*"
